/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 american_road.glb 
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/american-road-179a1e6a0a154031a60f300fc73d9dd8
Title: American Road
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Road(props) {
  const { nodes, materials } = useGLTF('../models/american_road.glb')
  return (
    <group {...props} dispose={null} rotation={[0,0.25,0]}>
      <group rotation={[-Math.PI / 1.95, 0, 0]}   position={[8,-15,10]} scale={0.1}>
        <mesh  receiveShadow geometry={nodes.Material2.geometry} material={materials.RoadLines} />
        <mesh  receiveShadow geometry={nodes.Material2_1.geometry} material={materials.Sidewalk01} />
        <mesh  receiveShadow geometry={nodes.Material2_2.geometry} material={materials.Grass02} />
      </group>
    </group>
  )
}

useGLTF.preload('../models/american_road.glb')
