/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bmw.glb 
Author: RBLXSupercars (https://sketchfab.com/RBLXSupercars)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2001-bmw-m3-gtr-21c04084b42149669b7300ece5ba86b5
Title: 2001 BMW M3-GTR
*/

import React, { useRef } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import { useThree } from 'react-three-fiber'
import { useLayoutEffect } from 'react';
import gsap from 'gsap';
import { useFrame } from 'react-three-fiber';
import { OrbitControls } from '@react-three/drei';

export function Car2(props) {
  const { nodes, materials } = useGLTF('../models/bmwsmall.glb');
  const grpref=useRef();

useFrame(()=>{
  grpref.current.rotation.y+=-0.05
})

  return (
    <group {...props} ref={grpref} dispose={null} scale={0.32}>
      <group position={[-9.987, -3, -1.981]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh castShadow geometry={nodes.Object_10.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        
        <mesh castShadow geometry={nodes.Object_2.geometry}   position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
      
        <mesh castShadow geometry={nodes.Object_23.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_25.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_26.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
  
        <mesh castShadow geometry={nodes.Object_3.geometry}   position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_30.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_4.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_5.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_6.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_7.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_8.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
        <mesh castShadow geometry={nodes.Object_9.geometry}  position={[-6.805, -0.466, 3.78]} ><meshBasicMaterial wireframe/></mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/bmwsmall.glb')
